import { useEffect, useState } from "react";
import { APIProvider, AdvancedMarker, Map } from "@vis.gl/react-google-maps";
import { MapPin, Navigation, Radio, ShieldCheck } from "lucide-react";
import logo from "./assets/pasabai-logo.png";
import { isSupabaseConfigured, supabase } from "./lib/supabase";

const mapsKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;
const davao = { lat: 7.0731, lng: 125.6128 };
const Button = ({ children, ...props }) => <button {...props} className="w-full rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{children}</button>;
const Field = ({ label, ...props }) => <label className="block text-sm font-semibold text-ink">{label}<input {...props} className="mt-1.5 w-full rounded-lg border border-primary/15 px-3 py-3 font-normal outline-none focus:border-primary" /></label>;
function Brand() { return <div className="flex items-center gap-3"><img src={logo} alt="PasaBai" className="h-11 w-11 rounded-lg object-contain" /><div><b className="text-xl text-primary"><span className="text-accent">Pasa</span>Bai</b><p className="text-xs text-muted">Student commute network</p></div></div>; }
function LiveMap({ drivers, selected, onSelect, point }) { if (!mapsKey) return <div className="grid h-64 place-items-center rounded-xl bg-card p-6 text-center text-sm text-muted">Add VITE_GOOGLE_MAPS_API_KEY to show the live Google Map and traffic.</div>; return <APIProvider apiKey={mapsKey}><div className="h-64 overflow-hidden rounded-xl"><Map defaultCenter={point || davao} defaultZoom={13} gestureHandling="greedy" disableDefaultUI>{drivers.map((d) => d.pickup_lat && <AdvancedMarker key={d.id} position={{ lat: d.pickup_lat, lng: d.pickup_lng }} onClick={() => onSelect?.(d)}><div className={`grid h-9 w-9 place-items-center rounded-full border-2 border-white ${selected?.id === d.id ? "bg-accent" : "bg-primary"} text-white`}><Navigation size={16} /></div></AdvancedMarker>)}{point && <AdvancedMarker position={point}><MapPin className="text-accent" /></AdvancedMarker>}</Map></div></APIProvider>; }
function Setup() { return <main className="mx-auto flex min-h-screen max-w-md flex-col justify-center bg-white p-7"><Brand /><h1 className="mt-10 text-2xl font-bold text-ink">Connect PasaBai to go live</h1><p className="mt-3 text-sm leading-6 text-muted">Add the three values in <code>.env.example</code>, then run <code>supabase/schema.sql</code> in Supabase.</p><div className="mt-6 space-y-3 rounded-xl bg-card p-4 text-sm"><p className="flex gap-2"><ShieldCheck size={18} />Secure driver and passenger accounts</p><p className="flex gap-2"><Radio size={18} />Real-time bookings and locations</p><p className="flex gap-2"><MapPin size={18} />Google Maps pickup points and traffic</p></div></main>; }
function Auth({ setSession }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [newUser, setNewUser] = useState(false); const [note, setNote] = useState(""); async function submit(e) { e.preventDefault(); const { data, error } = newUser ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); setNote(error?.message || (newUser ? "Confirm your email, then sign in." : "Welcome back.")); if (data.session) setSession(data.session); } return <main className="mx-auto flex min-h-screen max-w-md flex-col justify-center bg-white p-7"><Brand /><h1 className="mt-12 text-2xl font-bold">{newUser ? "Join PasaBai" : "Welcome back"}</h1><form onSubmit={submit} className="mt-7 space-y-4"><Field label="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /><Field label="Password" type="password" minLength="6" value={password} onChange={(e) => setPassword(e.target.value)} required /><Button>{newUser ? "Create account" : "Sign in"}</Button></form><p className="mt-4 text-sm text-primary">{note}</p><button onClick={() => setNewUser(!newUser)} className="mt-4 text-sm font-bold text-primary">{newUser ? "Sign in instead" : "Create an account"}</button></main>; }
function AppScreen({ session, profile, refresh }) { const [drivers, setDrivers] = useState([]); const [selected, setSelected] = useState(null); const [pickup, setPickup] = useState(""); const [dropoff, setDropoff] = useState(""); const [note, setNote] = useState(""); const load = () => supabase.from("profiles").select("*").eq("role", "driver").eq("is_available", true).then(({ data }) => setDrivers(data || [])); useEffect(() => { load(); const c = supabase.channel("pasabai-live").on("postgres_changes", { event: "*", schema: "public", table: "profiles" }, load).subscribe(); return () => supabase.removeChannel(c); }, []); async function online() { navigator.geolocation?.getCurrentPosition(async ({ coords }) => { await supabase.from("profiles").update({ is_available: !profile.is_available, pickup_lat: coords.latitude, pickup_lng: coords.longitude, pickup_label: "Current driver location" }).eq("id", session.user.id); refresh(); }); } async function book(e) { e.preventDefault(); if (!selected) return setNote("Choose a driver first."); const date = new Date(); await supabase.from("bookings").insert({ passenger_id: session.user.id, driver_id: selected.id, pickup_label: pickup, dropoff_label: dropoff, scheduled_for: date.toISOString() }); setNote("Booking sent. Live location is shared after acceptance."); } return <main className="mx-auto min-h-screen max-w-md bg-appbg pb-8"><header className="flex items-center justify-between bg-white p-5"><Brand /><button onClick={() => supabase.auth.signOut()} className="text-sm font-bold text-accent">Log out</button></header><section className="p-5"><h1 className="text-2xl font-bold">Hi, {profile.full_name}</h1>{profile.role === "driver" ? <><Button onClick={online} className="mt-5">{profile.is_available ? "Go offline" : "Go online and share pickup point"}</Button><p className="mt-3 text-sm text-muted">Location sharing ends when you go offline. Booking requests arrive in real time.</p></> : <><div className="mt-5"><LiveMap drivers={drivers} selected={selected} onSelect={setSelected} /></div><form onSubmit={book} className="mt-5 space-y-4 rounded-xl bg-white p-4"><b>Book a student driver</b><Field label="Pickup point" value={pickup} onChange={(e) => setPickup(e.target.value)} required /><Field label="Destination" value={dropoff} onChange={(e) => setDropoff(e.target.value)} required /><Button>Request ride for today</Button><p className="text-sm text-primary">{note}</p></form></>}</section></main>; }
export default function App() { const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const refresh = () => supabase.from("profiles").select("*").eq("id", session.user.id).maybeSingle().then(({ data }) => setProfile(data)); useEffect(() => { if (!supabase) return; supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => data.subscription.unsubscribe(); }, []); useEffect(() => { if (session) refresh(); else setProfile(null); }, [session]); if (!isSupabaseConfigured) return <Setup />; if (!session) return <Auth setSession={setSession} />; if (!profile) return <main className="p-8">Create your profile in Supabase, then refresh.</main>; return <AppScreen session={session} profile={profile} refresh={refresh} />; }
